version: '2'
services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    # - "./mysql:/var/lib/mysql"

  php:
    build: ./php
    ports:
      - '8080:80'
    volumes:
      - ./public:/var/www/html
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: pass
    links:
      - mysql:mysql
    ports:
      - 18080:80
    volumes:
      - pma_sessions:/sessions
volumes:
  db:
  pma_sessions: